### ISSUE TITLE
Failed to install fmpeg on Kaggle if running TPU 

### ISSUE THREAD

**Issue by marco-cheung** [sanchit-gandhi/whisper-jax#116]
I want to do transcription on my own audio file, but the environment requied me to install ffmpeg.

Then I catch this error:
**ValueError: ffmpeg was not found but is required to load audio files from filename**

Accelerator used: TPU  VM v3-8
Installed package: transformers==4.28.0

**Comment by DebarshiChanda** [comment]
```
!apt update
!apt install ffmpeg -y
```
Execute these commands to install ffmpeg

**Comment by marco-cheung** [comment]
Problem solved, thanks!
