### ISSUE TITLE
Does Whisper-Jax come with no cost for enterprise usage?

### ISSUE THREAD

**Issue by lalithhakari** [sanchit-gandhi/whisper-jax#145]
If I decide to integrate it into our production process for an enterprise-level application, could you please provide information on the pricing for its usage?

**Comment by MaximeDde** [comment]
I would like an answer to this question too, if possible...!

**Comment by gl-jkeys** [comment]
The lone correct answer is that _only_ a licensed legal practitioner in your jurisdiction is qualified to navigate complex issues like licensing and intellectual property, especially as it pertains to anyone's unique situation. You should direct your question to such a practitioner, and not rely on answers provided in a public forum like this one.

That said, the OpenAI Whisper code, model, and weights were released under MIT license, and this repository is covered by an Apache 2.0 license. 

I am not a lawyer and this comment does not constitute legal advice :D

**Comment by sanchit-gandhi** [comment]
Couldn't have said it better than @gl-jkeys! Everything on our side is set-up for free enterprise usage (MIT license for the model + Apache2 for the code), so you should ensure your use case adheres to these license agreements
