### ISSUE TITLE
Bug: Numpy array as input

### ISSUE THREAD

**Issue by knoriy** [sanchit-gandhi/whisper-jax#15]
When a Numpy array is passed in, the model runs fine, but this causes the model to perform poorly because the audio array is not resampled to the appropriate sample rate.

This is fixed by passing a dict with `array` and `sampling_rate` keys.

**Comment by sanchit-gandhi** [comment]
Hey @knoriy - this is explained a bit more in the docstring: https://github.com/sanchit-gandhi/whisper-jax/blob/8244d43d2aad61cf88a2e02142799b01ae72681a/whisper_jax/pipeline.py#L429

In short, with just a 1-d NumPy audio array, there's no way of knowing the sampling rate of the audio file, so it's assumed to already be at the correct sampling rate. We recommend passing the inputs as a dict to allow the pipeline to resample if necessary.

**Comment by knoriy** [comment]
Ahh, sorry, I missed that detail in the docs.

I think It would be best to require a `dict` in the case where Numpy arrays are passed in and have a check in place to see if the sample rate is correct, else, resample the Numpy array.

https://github.com/sanchit-gandhi/whisper-jax/blob/8244d43d2aad61cf88a2e02142799b01ae72681a/whisper_jax/pipeline.py#L280:~:text=if%20isinstance(inputs%2C%20dict,ratio%20%3D%201

The code here already handles this very well, as Librosa is able to handle Numpy correctly.

Please let me know what you thought about this :)

**Comment by sanchit-gandhi** [comment]
I think we can add a warning when a bare NumPy array is passed informing the user that no resampling operations are performed and the code may be prone to silent errors?

**Comment by knoriy** [comment]
> I think we can add a warning when a bare NumPy array is passed informing the user that no resampling operations are performed and the code may be prone to silent errors?
> 
> This way we gently nudge the user to use `dicts` or resample themselves outside of the pipeline

That sounds good :). The warning would be really useful.

Also, thank you for the work you and everyone involved have done with WhisperJax
