### ISSUE TITLE
Is there any way to reduce the first jit compile time

### ISSUE THREAD

**Issue by ILG2021** [sanchit-gandhi/whisper-jax#150]
Can we store the compile code or weights directly and load it later. That may solve the boring first jit compile.

**Comment by sanchit-gandhi** [comment]
Yes we can use the [compilation cache](https://gist.github.com/shawwn/16d89ea5121d10214459238225453b13), _c.f._ this Kaggle notebook: https://www.kaggle.com/code/sgandhi99/whisper-jax-tpu
