### ISSUE TITLE
Cannot instantiate FlaxWhisperPipline with parameters anymore

### ISSUE THREAD

**Issue by angediablo** [sanchit-gandhi/whisper-jax#155]
I am facing the following issue since yesterday:

Pipeline cannot be instantiated with the model nor any other parameters such as bloat and batch size.
 
 `pipeline = FlaxWhisperPipline("openai/whisper-large-v2", dtype=jnp.bfloat16, batch_size=16)`

is raising the following error:

> ValueError: `params` cannot be accessed from model when the model is created with `_do_init=False`. You must call `init_weights` manually and store the params outside of the model and pass it explicitly where needed.

It seems like there has been a library update somewhere but I cannot identify the exact root cause. I have found a similar error declaration in https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_flax_utils.py

`    def params(self) -> Union[Dict, FrozenDict]:
        if not self._is_initialized:
            raise ValueError(
                "`params` cannot be accessed from model when the model is created with `_do_init=False`. "
                "You must call `init_weights` manually and store the params outside of the model and "
                "pass it explicitly where needed."
            )
        return self._params`

Is there any workaround available?

No error is raised when pipeline is initiated without any parameters
pipeline = FlaxWhisperPipline()

How can the model and parameters be assigned afterwards ?

My last successful execution was on October 31st.

**Comment by WillHu** [comment]
I met the same problem just now. Cuda11.8, cudnn 8.9

**Comment by nftblackmagic** [comment]
Same problem

**Comment by angediablo** [comment]
> Same problem
> 
> Found a WAR. Just decrease the transformers version to !pip install transformers==4.31.0
> 
> I think the latest transformers version cause the issue.

Good looking out @nftblackmagic !

Reverting to that transformers version fixes the issue.

Thanks!

**Comment by sanchit-gandhi** [comment]
Thanks for flagging @angediablo! As @nftblackmagic correctly pointed out, there's a breaking change with Transformers 4.35 that we need to fix upstream: https://github.com/sanchit-gandhi/whisper-jax/pull/160/files#r1407790668

Closing this for now as we have the 'hot fix'. Will link the full PR that corrects this behaviour when ready!
