### ISSUE TITLE
Adaptation for Whisper-Large-V3 model

### ISSUE THREAD

**Issue by s-tomar** [sanchit-gandhi/whisper-jax#158]
Hi,

Thank you for sharing your work with the OS-community.

I encountered an issue for the latest large-v3 model that was released by OpenAI on 6th November. It pertains to the value of num_mel_bin. The code given in the section https://github.com/sanchit-gandhi/whisper-jax#model-usage, adapted according to your response given for issue https://github.com/sanchit-gandhi/whisper-jax/issues/70, fails with the following error:
`ValueError: input_features.shape[1:], must be equal to (self.config.num_mel_bins, self.config.max_source_positions * 2) (got (80, 3000), but should be (128, 3000))`

After some digging, I found that it has to do with the parameter **num_mel_bin**. For large-v3 model, this value should be **128** (see https://huggingface.co/openai/whisper-large-v3) instead of **80**, the latter being the default value for all the remaining models (tiny, base, small, medium, large-v1, and large-v2).

In two of the files of the implementation, namely, pipeline.py (line #117), and modeling_flax_whisper.py (line #1000), there is this definition/initiation `input_shape: Tuple[int] = (1, 80, 3000)`

Could you be kind enough to guide a solution? In particular, if I wish to have CPU only, or a low GPU (local, consumer-grade) implementation, which should work for all the model sizes (whether num_mel_bins is 80 or 128).

Thanks in advance.

**Comment by peregilk** [comment]
I have tried updating modeling_flax_whisper.py in the same way as here: https://github.com/huggingface/transformers/pull/27360/files/59b6fdc4ba145047ff7d57898e772c2d5ad91e40. And I have also tried updating in pipeline.py so that the input shape is correct. However, I am still having a mismatch here.

Anything else that needs to be changed @sanchit-gandhi?

**Comment by sanchit-gandhi** [comment]
Closed by #160 - it should work after this fix
