### ISSUE TITLE
Where to put model in local install

### ISSUE THREAD

**Issue by remybonnav** [sanchit-gandhi/whisper-jax#17]
I don't get how I can link to the model on a local indtall. Should I replace /openai/largev2/ by the path of my model on the disk?
And should I download all feom the folder from huggingface or should I just download the flax file?

**Comment by sanchit-gandhi** [comment]
Hey @remybonnav!

Cool to see that you're using the Whisper JAX repo 🤗 You have two options for using your own checkpoint:
1. Replace `openai/large-v2` with the id of your checkpoint on the Hugging Face Hub, e.g. for [this checkpoint](https://huggingface.co/sanchit-gandhi/whisper-small-hi), I would use `sanchit-gandhi/whisper-small-hi`
2. Download the **entire** repository to your local system, and then pass the path to this folder. E.g. if I cloned [this checkpoint](https://huggingface.co/sanchit-gandhi/whisper-small-hi) into a folder called `whisper-small-hi`, I would pass `./whisper-small-hi`

**Comment by remybonnav** [comment]
Great, thanks, I was not sure how to replace path to huggingface by a path to local folder. Thanks again
