### ISSUE TITLE
Slow post processing

### ISSUE THREAD

**Issue by RezaTokhshid** [sanchit-gandhi/whisper-jax#184]
Hi

I'm having trouble reproducing the benchmarks on TPU (I'm on V3-8)

It's taking 19s or so to transcribe a 15min audio.
I checked and the **post processing** is taking too long. (Preprocessing is also slower than the demo you have around 3 seconds)

This line to be specific is taking around 12s
```python
text, optional = self.tokenizer._decode_asr(
            model_outputs,
            return_timestamps=return_timestamps,
            return_language=return_language,
            time_precision=time_precision,
)
```

With the 3s on `forward` it'll turn out around 19-20 seconds.

Do you have  any tips on how to speed up the steps around `forward`?

**Comment by sanchit-gandhi** [comment]
Fixed by #189!
