### ISSUE TITLE
HuggingFace space erroring more often than usual

### ISSUE THREAD

**Issue by iGerman00** [sanchit-gandhi/whisper-jax#188]
Hey @sanchit-gandhi, awesome tool and awesome space. I use it to transcribe things sometimes. Since recently I've been getting a lot of errors, I reckon something like this:  

![ishare-1711287491](https://github.com/sanchit-gandhi/whisper-jax/assets/36676880/de96a6ea-7389-42ad-a80b-8db9610047ff)

Could you please take a look at the space? Maybe there's some memory leak or it's filled with cached data or something..

**Comment by sanchit-gandhi** [comment]
Thanks for the ping - indeed looks like a memory leak. I've wiped the TPUs and we're running as usual again
