### ISSUE TITLE
Jax installation Consulting

### ISSUE THREAD

**Issue by standyyyy** [sanchit-gandhi/whisper-jax#2]
Hi,
 I'm glad to have discovered this place, and after hearing how much speed can be increased, I can't wait to give it a try

Is Jax only installed on Linux？

Please forgive my poor English, the above is translated

**Comment by sanchit-gandhi** [comment]
Hey @standyyyy, thanks for the interest in Whisper-JAX! You can refer to the official JAX installation guide for all the details on OS compatibility and installation instructions: https://github.com/google/jax#installation I recommend you follow this guide for installing JAX
