### ISSUE TITLE
Add train code

### ISSUE THREAD

**Issue by ILG2021** [sanchit-gandhi/whisper-jax#43]
Thanks for you nice project. The openai whisper don't open source the train code. Can you project implement it? When I use large-v2 model, it always gives youtube video advertise. So it is a problem of the train data. I want to train a model with clean data. The problem is discussed below:
https://github.com/openai/whisper/discussions/928

**Comment by sanchit-gandhi** [comment]
Hey @ILG2021 - regarding the training process, OpenAI curated the dataset by web scraping the internet for audio data. Unfortunately, these are all the details we know about it from the [Whisper paper](https://arxiv.org/pdf/2212.04356.pdf). They subsequently trained 11 speech recognition models on this data. They released all of the models, but not the dataset. The dataset remains private and as fair as we know is not going to be made open-source. So OpenAI are the only ones with access to it and the only ones who can re-train the model.

You can, however, fine-tune the model: https://huggingface.co/blog/fine-tune-whisper
With very little data (10-20 hours), you can successfully change the transcription properties of the Whisper model. What I suggest you try doing is fine-tuning Whisper on 10-20 hours of 'clean' data and checking the results.

**Comment by ILG2021** [comment]
Ok, thank you.
