### ISSUE TITLE
OpenAI and Transformers Benchmarks

### ISSUE THREAD

**Issue by noob-cod** [sanchit-gandhi/whisper-jax#53]
Hello, I want to confirm whether the implementation of OpenAI in the benchmark uses the openai-whisper library or the WhisperForConditionalGeneration model of Hugging Face? At the same time, I also want to confirm whether the Hugging Face implementation uses the FlaxWhipserForConditionalGeneration model?

If the OpenAI implementation uses the model in openai-whisper, is the performance test the execution time of DecodingTask.run()?

**Comment by sanchit-gandhi** [comment]
Hey! It uses:
1. OpenAI's Whisper `whisper.transcribe`: https://github.com/openai/whisper
2. Transformers' pipeline: https://huggingface.co/openai/whisper-large-v2#long-form-transcription (with `batch_size=16`)
3. Whisper JAX (this repo)

**Comment by noob-cod** [comment]
Thanks for your reply!
