### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by secondbrain-note** [sanchit-gandhi/whisper-jax#58]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/sanchit-gandhi/whisper-jax.git /private/var/folders/nl/lb6vjd_x22sg124_rpd1kqrh0000gn/T/pip-req-build-_e68d4vt did not run successfully.
│ exit code: 128
╰─> See above for output.

**Comment by sanchit-gandhi** [comment]
Hey @secondbrain-note - do you want to clone the repo or pip install it from main?

Clone:
```
git clone https://github.com/sanchit-gandhi/whisper-jax.git
cd whisper-jax
pip install -e .
```

Pip install from main:
```
pip install git+https://github.com/sanchit-gandhi/whisper-jax.git
```

**Comment by secondbrain-note** [comment]
> 

Thank you for your patience. I previously installed it by pip install in the macos terminal and report the bug above. Today I try to install it in VS Code and no bug is reported. I am not a programmer, so sorry for such a silly question.

**Comment by sanchit-gandhi** [comment]
Glad it's fixed!
