### ISSUE TITLE
Runtime Error: jaxlib version on GoogleColab

### ISSUE THREAD

**Issue by abhinavasr** [sanchit-gandhi/whisper-jax#63]
RuntimeError: jaxlib is version 0.3.25, but this version of jax requires version >= 0.4.7.

Full Log:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-5-dff9e3082fd1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from whisper_jax import FlaxWhisperPipline
      2 
      3 # instantiate pipeline
      4 pipeline = FlaxWhisperPipline("openai/whisper-large-v2")
      5 

8 frames
[/usr/local/lib/python3.10/dist-packages/jax/_src/lib/__init__.py](https://localhost:8080/#) in check_jaxlib_version(jax_version, jaxlib_version, minimum_jaxlib_version)
     60     msg = (f'jaxlib is version {jaxlib_version}, but this version '
     61            f'of jax requires version >= {minimum_jaxlib_version}.')
---> 62     raise RuntimeError(msg)
     63 
     64   if _jaxlib_version > _jax_version:

RuntimeError: jaxlib is version 0.3.25, but this version of jax requires version >= 0.4.7.

**Comment by sanchit-gandhi** [comment]
Recommended to use the Kaggle notebook for running on TPU: https://www.kaggle.com/code/sgandhi99/whisper-jax-tpu

Colab TPU doesn't support the latest versions of JAX.
