### ISSUE TITLE
Setting number of thread under JAX

### ISSUE THREAD

**Issue by AlexandderGorodetski** [sanchit-gandhi/whisper-jax#69]
Hello guys,

Under Whisper it is possible to define number of decoding threads using following python code

    torch.set_num_threads(nj)
    model = whisper.load_model(model_type)

In this case if I am working on machine only with CPUs all CPUs are working in 100%.

Is there similar mechanism in JAX ?

Thanks a lot,
AlexG.

**Comment by sanchit-gandhi** [comment]
Hey @AlexandderGorodetski - see section on batching: https://github.com/sanchit-gandhi/whisper-jax#batching
