### ISSUE TITLE
EdgeTPU

### ISSUE THREAD

**Issue by etlweather** [sanchit-gandhi/whisper-jax#71]
Sorry if that's an obvious question - would that run on any EdgeTPU - something you can run off-line on your machine without using cloud services such as [Coral TPU](https://coral.ai/products/)?

**Comment by sanchit-gandhi** [comment]
If you can run JAX on EdgeTPU then it should work, yes!

**Comment by sanchit-gandhi** [comment]
Looks like Coral doesn't support JAX unfortunately: https://github.com/google-coral/edgetpu/issues/621
