### ISSUE TITLE
HF-Ttransformers

### ISSUE THREAD

**Issue by AlexandderGorodetski** [sanchit-gandhi/whisper-jax#75]
Hello guys,

In your benchmarks section you mention following compared systems:

OpenAI
HF-Transforemers
JAX

Could you please point me to some examples that shows how to run HF-Transformers transcribe task.

Thanks a lot,
AlexG.

**Comment by sanchit-gandhi** [comment]
See https://huggingface.co/openai/whisper-large-v2#long-form-transcription
