### ISSUE TITLE
How to fine tune teh whisper-jax 

### ISSUE THREAD

**Issue by abdelkareemkobo** [sanchit-gandhi/whisper-jax#79]
I am new to transformers and big models and was searching i first find whisper and, I am reading your very helpful blog about fine-tuning whisper with pytorch and hindi in the hugging face and i want to fine tune it in a different langauge but want to use the jax implementation can you guide me how to this and thanks for your work it's very inspiring

**Comment by thisiskeithkwan** [comment]
I would like to know too

**Comment by snoop2head** [comment]
I think the code is available here: https://github.com/huggingface/transformers/tree/main/examples/flax/speech-recognition

Resulting checkpoint from the code above is here too: https://huggingface.co/sanchit-gandhi/whisper-small-hi-flax

**Comment by sanchit-gandhi** [comment]
That's exactly the right reference! Thanks @snoop2head!
