### ISSUE TITLE
How to Accelerate Transcription of Short Audio

### ISSUE THREAD

**Issue by yangsuxia** [sanchit-gandhi/whisper-jax#86]
If I want to decode short audio within 5 seconds, how can I accelerate it?

I looked at the code and found that when inputting a short audio within 5 seconds, first padding it to 30 seconds before extracting features for forward. Does this mean that only audio greater than 30 seconds will have a faster speed, which is not suitable for short audio.

**Comment by asr-lord** [comment]
Hi, check out this related issue: https://github.com/sanchit-gandhi/whisper-jax/issues/66

**Comment by yangsuxia** [comment]
> Hi, check out this related issue: #66

thanks！
