### ISSUE TITLE
Installation problem on MAC

### ISSUE THREAD

**Issue by AlexandderGorodetski** [sanchit-gandhi/whisper-jax#89]
Hello guys,

I am trying to install CPU version of whisper_jax on my MAC.

I used following commands for the installation

pip install --upgrade pip
pip install --upgrade "jax[cpu]"

It seems that everything was installed properly.

But after I run python I have following error

>>> from whisper_jax import FlaxWhisperPipline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'whisper_jax'

Note that on Linux above installation is working properly.

Could you help please,
Thanks,
AlexG.

**Comment by asr-lord** [comment]
Did you run: `pip install git+https://github.com/sanchit-gandhi/whisper-jax.git`?

**Comment by AlexandderGorodetski** [comment]
Yes, this solved the problem. Thank you.
